import { useState, useEffect } from 'react';
import Elementor from '../components/Elementor.tsx';
import AtomModel from '../components/AtomModel.tsx';
import {
  loadCustomElements, saveCustomElement, deleteCustomElement,
  type CustomElement,
} from '../engine/storage.ts';
import { playCorrect, playCollect } from '../engine/sounds.ts';

interface ElementLabScreenProps {
  onBack: () => void;
  playerName?: string;
}

type LabPhase = 'gallery' | 'creator';

const CATEGORIES = [
  { value: 'superheavy', label: 'Superheavy Metal', emoji: '🏋️' },
  { value: 'magical', label: 'Magical Element', emoji: '✨' },
  { value: 'alien', label: 'Alien Element', emoji: '👽' },
  { value: 'mysterious', label: 'Mysterious Substance', emoji: '🌀' },
  { value: 'metal', label: 'Metal', emoji: '🔩' },
  { value: 'nonmetal', label: 'Non-metal', emoji: '💨' },
  { value: 'noble-gas', label: 'Noble Gas', emoji: '🫧' },
  { value: 'radioactive', label: 'Radioactive', emoji: '☢️' },
];

const STATES = ['Solid', 'Liquid', 'Gas', 'Plasma'];

const COLORS = [
  '#ff6b6b', '#ee5a24', '#f9ca24', '#6ab04c', '#22a6b3',
  '#4834d4', '#be2edd', '#eb4d4b', '#7ed6df', '#e056fd',
  '#686de0', '#30336b', '#95afc0', '#f8a5c2', '#63cdda',
];

const SUPERPOWERS = [
  'Can turn invisible when nobody is looking',
  'Glows in the dark with an eerie light',
  'Makes anything it touches bounce',
  'Can change colour depending on mood',
  'Emits a calming hum at midnight',
  'Attracts butterflies from miles away',
  'Makes nearby objects float briefly',
  'Tastes like strawberries (do NOT eat!)',
  'Creates tiny rainbows in sunlight',
  'Can record sounds and play them back',
  'Vibrates at the frequency of happiness',
  'Turns water into sparkling fizzy water',
  'Makes flowers bloom instantly nearby',
  'Can freeze time for 0.001 seconds',
  'Whispers the secrets of the universe',
];

const IMAGINARY_COMPOUNDS = [
  (name: string, sym: string) => [`${sym}O₂ (${name} oxide)`, `${sym}Cl₃ (${name} chloride)`, `${sym}₂S (${name} sulphide)`],
  (name: string, sym: string) => [`${sym}F₄ (${name} fluoride)`, `${sym}(OH)₂ (${name} hydroxide)`],
  (name: string, sym: string) => [`${sym}₃N (${name} nitride)`, `${sym}CO₃ (${name} carbonate)`, `${sym}₂O₅ (${name} pentoxide)`],
];

const IMAGINARY_USES = [
  ['Powering starships on long voyages', 'Making super-bouncy trampolines', 'Flavouring interstellar ice cream'],
  ['Building unbreakable shields', 'Painting walls that change colour', 'Creating holograms you can touch'],
  ['Fueling rocket boots', 'Making clouds glow at night', 'Generating force fields for pillow forts'],
  ['Crafting ultra-light armour', 'Powering teleportation devices', 'Growing crystals that sing'],
];

const IMAGINARY_OBTAINED = [
  'Found deep inside enchanted volcanoes on distant moons.',
  'Mined from the cores of rainbow comets that pass Earth every 1,000 years.',
  'Distilled from the morning dew on a field of singing flowers.',
  'Extracted from the sparks generated by laughing lightning bolts.',
  'Collected from the rings of Saturn by robotic bees.',
  'Grown in secret underwater gardens tended by jellyfish.',
  'Harvested from wish-powered crystals found inside hollow mountains.',
];

const IMAGINARY_EXTRA_FACTS = [
  'Scientists believe it may hold the key to faster-than-light travel.',
  'When cooled to absolute zero, it hums a mysterious melody.',
  'It changes colour on your birthday — nobody knows why.',
  'Some researchers claim it can read your mood from across a room.',
  'It was once used by ancient aliens to build their pyramids.',
  'Under a full moon, it sparkles with tiny flashes of lightning.',
  'If you put two pieces together they spin in opposite directions forever.',
  'It is the only substance known to make cats and dogs get along.',
];

function pickRandom<T>(arr: T[], count: number): T[] {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

/** Auto-generate imaginative extended data for a custom element */
function generateExtendedData(atomicNumber: number, name: string, symbol: string, category: string) {
  const mass = atomicNumber + Math.round(Math.random() * 80 + 40); // plausible crazy mass
  const period = 8 + Math.floor((atomicNumber - 119) / 18);
  const group = ((atomicNumber - 119) % 18) + 1;
  const blocks = ['s', 'p', 'd', 'f', 'g'];
  const block = blocks[Math.floor(Math.random() * blocks.length)];
  const shells = [2, 8, 18, 32, 32, 18, 8];
  let remaining = atomicNumber;
  const config: string[] = [];
  for (let i = 0; i < shells.length && remaining > 0; i++) {
    const n = Math.min(remaining, shells[i]);
    config.push(`${n}`);
    remaining -= n;
  }
  if (remaining > 0) config.push(`${remaining}`);
  const electronConfiguration = config.join('.');

  const isRadioactive = category === 'radioactive' || Math.random() > 0.5;
  const halfLifeOptions = ['0.003 seconds', '42 minutes', '7.7 hours', '3,000 years', '1 million years', '∞ (theoretical)'];

  const compoundSet = IMAGINARY_COMPOUNDS[Math.floor(Math.random() * IMAGINARY_COMPOUNDS.length)];
  const useSet = IMAGINARY_USES[Math.floor(Math.random() * IMAGINARY_USES.length)];

  return {
    atomicMass: mass,
    period,
    group,
    block: `${block}-block`,
    electronConfiguration,
    radioactive: isRadioactive,
    halfLife: isRadioactive ? halfLifeOptions[Math.floor(Math.random() * halfLifeOptions.length)] : undefined,
    compounds: compoundSet(name, symbol),
    uses: useSet,
    obtainedFrom: IMAGINARY_OBTAINED[Math.floor(Math.random() * IMAGINARY_OBTAINED.length)],
    additionalFacts: pickRandom(IMAGINARY_EXTRA_FACTS, 2),
  };
}

function randomSuperpower(): string {
  return SUPERPOWERS[Math.floor(Math.random() * SUPERPOWERS.length)];
}

export default function ElementLabScreen({ onBack, playerName }: ElementLabScreenProps) {
  const [phase, setPhase] = useState<LabPhase>('gallery');
  const [customElements, setCustomElements] = useState<CustomElement[]>([]);
  const [selectedEl, setSelectedEl] = useState<CustomElement | null>(null);

  // Creator form state
  const [elName, setElName] = useState('');
  const [elSymbol, setElSymbol] = useState('');
  const [elCategory, setElCategory] = useState('superheavy');
  const [elState, setElState] = useState('Solid');
  const [elColor, setElColor] = useState('#4834d4');
  const [elSuperpower, setElSuperpower] = useState(randomSuperpower());
  const [elFunFact, setElFunFact] = useState('');

  useEffect(() => {
    setCustomElements(loadCustomElements());
  }, []);

  const nextNumber = customElements.length > 0
    ? Math.max(...customElements.map(e => e.atomicNumber)) + 1
    : 119;

  const resetForm = () => {
    setElName('');
    setElSymbol('');
    setElCategory('superheavy');
    setElState('Solid');
    setElColor('#4834d4');
    setElSuperpower(randomSuperpower());
    setElFunFact('');
  };

  const handleCreate = () => {
    if (!elName.trim() || !elSymbol.trim()) return;
    const sym = elSymbol.trim().slice(0, 2);
    const finalSymbol = sym.charAt(0).toUpperCase() + sym.slice(1).toLowerCase();
    const extended = generateExtendedData(nextNumber, elName.trim(), finalSymbol, elCategory);
    const newEl: CustomElement = {
      id: Date.now().toString(36) + Math.random().toString(36).slice(2, 7),
      atomicNumber: nextNumber,
      symbol: finalSymbol,
      name: elName.trim(),
      category: elCategory,
      stateAtRoomTemp: elState,
      color: elColor,
      superpower: elSuperpower,
      funFact: elFunFact.trim() || `${elName.trim()} was discovered in a secret laboratory!`,
      discoveredBy: playerName || 'Unknown Scientist',
      createdAt: new Date().toISOString(),
      ...extended,
    };
    saveCustomElement(newEl);
    setCustomElements(loadCustomElements());
    playCollect();
    resetForm();
    setPhase('gallery');
  };

  const handleDelete = (id: string) => {
    deleteCustomElement(id);
    setCustomElements(loadCustomElements());
    setSelectedEl(null);
  };

  // --- Detail overlay ---
  if (selectedEl) {
    const selCat = CATEGORIES.find(c => c.value === selectedEl.category);
    const discoveryDate = selectedEl.createdAt ? new Date(selectedEl.createdAt).toLocaleDateString() : 'Unknown';
    return (
      <div className="el-lab">
        <div className="el-lab-detail">
          <button className="back-btn" onClick={() => setSelectedEl(null)}>&larr; Back</button>

          <div className="el-lab-detail-tile" style={{ background: selectedEl.color }}>
            <span className="el-lab-tile-number">{selectedEl.atomicNumber}</span>
            <span className="el-lab-tile-symbol">{selectedEl.symbol}</span>
            <span className="el-lab-tile-name">{selectedEl.name}</span>
            {selectedEl.atomicMass && <span className="el-lab-tile-mass">{selectedEl.atomicMass}</span>}
          </div>

          <div className="atom-model-container">
            <AtomModel atomicNumber={selectedEl.atomicNumber} symbol={selectedEl.symbol} size={180} />
            <p className="atom-model-label">Bohr Model — {selectedEl.atomicNumber} electron{selectedEl.atomicNumber !== 1 ? 's' : ''}</p>
          </div>

          <div className="el-lab-detail-rows">
            <div className="el-lab-row"><span className="el-lab-label">Category</span><span>{selCat?.emoji} {selCat?.label}</span></div>
            <div className="el-lab-row"><span className="el-lab-label">State</span><span>{selectedEl.stateAtRoomTemp}</span></div>
            {selectedEl.period && <div className="el-lab-row"><span className="el-lab-label">Period</span><span>{selectedEl.period}</span></div>}
            {selectedEl.group && <div className="el-lab-row"><span className="el-lab-label">Group</span><span>{selectedEl.group}</span></div>}
            {selectedEl.block && <div className="el-lab-row"><span className="el-lab-label">Block</span><span>{selectedEl.block}</span></div>}
            {selectedEl.electronConfiguration && <div className="el-lab-row"><span className="el-lab-label">Electron Config</span><span>{selectedEl.electronConfiguration}</span></div>}
            <div className="el-lab-row"><span className="el-lab-label">Superpower</span><span>{selectedEl.superpower}</span></div>
            {selectedEl.radioactive !== undefined && (
              <div className="el-lab-row"><span className="el-lab-label">Radioactive</span><span>{selectedEl.radioactive ? `Yes (half-life: ${selectedEl.halfLife})` : 'No'}</span></div>
            )}
            <div className="el-lab-row"><span className="el-lab-label">Discovered By</span><span>{selectedEl.discoveredBy}</span></div>
            <div className="el-lab-row"><span className="el-lab-label">Date Discovered</span><span>{discoveryDate}</span></div>

            {selectedEl.compounds && selectedEl.compounds.length > 0 && (
              <div className="el-lab-row"><span className="el-lab-label">Common Compounds</span><span>{selectedEl.compounds.join(', ')}</span></div>
            )}

            {selectedEl.uses && selectedEl.uses.length > 0 && (
              <div className="el-lab-section">
                <span className="el-lab-label">Uses</span>
                <ul className="el-lab-list">
                  {selectedEl.uses.map((use, i) => <li key={i}>{use}</li>)}
                </ul>
              </div>
            )}

            {selectedEl.obtainedFrom && (
              <div className="el-lab-section">
                <span className="el-lab-label">How It's Obtained</span>
                <p className="el-lab-text">{selectedEl.obtainedFrom}</p>
              </div>
            )}

            <div className="el-lab-section">
              <span className="el-lab-label">Fun Fact</span>
              <p className="el-lab-text">{selectedEl.funFact}</p>
            </div>

            {selectedEl.additionalFacts && selectedEl.additionalFacts.length > 0 && (
              <div className="el-lab-section">
                <span className="el-lab-label">More Facts</span>
                <ul className="el-lab-list">
                  {selectedEl.additionalFacts.map((fact, i) => <li key={i}>{fact}</li>)}
                </ul>
              </div>
            )}
          </div>
          <button className="back-btn el-lab-delete" onClick={() => handleDelete(selectedEl.id)}>Delete Element</button>
        </div>
      </div>
    );
  }

  // --- Creator form ---
  if (phase === 'creator') {
    return (
      <div className="el-lab">
        <button className="back-btn" onClick={() => setPhase('gallery')}>&larr; Back to Gallery</button>
        <h2 className="el-lab-title">Create Element #{nextNumber}</h2>

        <div className="el-lab-preview" style={{ background: elColor }}>
          <span className="el-lab-tile-number">{nextNumber}</span>
          <span className="el-lab-tile-symbol">{elSymbol ? (elSymbol.charAt(0).toUpperCase() + elSymbol.slice(1, 2).toLowerCase()) : '??'}</span>
          <span className="el-lab-tile-name">{elName || 'Your Element'}</span>
        </div>

        <div className="el-lab-form">
          <label className="el-lab-field">
            <span>Element Name</span>
            <input type="text" value={elName} onChange={e => setElName(e.target.value)} placeholder="e.g. Blazium" maxLength={20} />
          </label>

          <label className="el-lab-field">
            <span>Symbol (1-2 letters)</span>
            <input type="text" value={elSymbol} onChange={e => setElSymbol(e.target.value.replace(/[^a-zA-Z]/g, ''))} placeholder="e.g. Bz" maxLength={2} />
          </label>

          <label className="el-lab-field">
            <span>Category</span>
            <div className="el-lab-categories">
              {CATEGORIES.map(cat => (
                <button
                  key={cat.value}
                  className={`el-lab-cat-btn ${elCategory === cat.value ? 'selected' : ''}`}
                  onClick={() => setElCategory(cat.value)}
                >
                  {cat.emoji} {cat.label}
                </button>
              ))}
            </div>
          </label>

          <label className="el-lab-field">
            <span>State at Room Temperature</span>
            <div className="el-lab-states">
              {STATES.map(s => (
                <button
                  key={s}
                  className={`el-lab-state-btn ${elState === s ? 'selected' : ''}`}
                  onClick={() => setElState(s)}
                >
                  {s}
                </button>
              ))}
            </div>
          </label>

          <label className="el-lab-field">
            <span>Colour</span>
            <div className="el-lab-colors">
              {COLORS.map(c => (
                <button
                  key={c}
                  className={`el-lab-color-btn ${elColor === c ? 'selected' : ''}`}
                  style={{ background: c }}
                  onClick={() => setElColor(c)}
                />
              ))}
            </div>
          </label>

          <label className="el-lab-field">
            <span>Superpower</span>
            <div className="el-lab-superpower-row">
              <input type="text" value={elSuperpower} onChange={e => setElSuperpower(e.target.value)} maxLength={80} />
              <button className="el-lab-reroll" onClick={() => { setElSuperpower(randomSuperpower()); playCorrect(); }} title="Random superpower">&#127922;</button>
            </div>
          </label>

          <label className="el-lab-field">
            <span>Fun Fact (optional)</span>
            <input type="text" value={elFunFact} onChange={e => setElFunFact(e.target.value)} placeholder="Something cool about your element..." maxLength={120} />
          </label>

          <button
            className="start-btn"
            onClick={handleCreate}
            disabled={!elName.trim() || !elSymbol.trim()}
          >
            Create Element!
          </button>
        </div>
      </div>
    );
  }

  // --- Gallery ---
  return (
    <div className="el-lab">
      <button className="back-btn" onClick={onBack}>&larr; Back</button>
      <h2 className="el-lab-title">&#129514; Element Lab</h2>
      <Elementor expression="greeting" message={customElements.length ? `You've created ${customElements.length} element${customElements.length > 1 ? 's' : ''}! Tap one to see details, or create a new one!` : 'Welcome to the Element Lab! Create your very own elements and add them to the periodic table!'} />

      <button className="start-btn el-lab-create-btn" onClick={() => { resetForm(); setPhase('creator'); }}>
        + Create New Element
      </button>

      {customElements.length > 0 && (
        <div className="el-lab-gallery">
          {customElements.map(el => (
            <button
              key={el.id}
              className="el-lab-gallery-tile"
              style={{ background: el.color }}
              onClick={() => setSelectedEl(el)}
            >
              <span className="el-lab-tile-number">{el.atomicNumber}</span>
              <span className="el-lab-tile-symbol">{el.symbol}</span>
              <span className="el-lab-tile-name">{el.name}</span>
            </button>
          ))}
        </div>
      )}

      {customElements.length === 0 && (
        <p className="el-lab-empty">No custom elements yet. Tap "Create New Element" to get started!</p>
      )}
    </div>
  );
}
